// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAGw--d0WMZQA4qxb1M6pXya34B8bnc-o',
    appId: '1:946278867566:web:cf0bf7839cb7ab8d413c7f',
    messagingSenderId: '946278867566',
    projectId: 'flutterschool-975b9',
    authDomain: 'flutterschool-975b9.firebaseapp.com',
    storageBucket: 'flutterschool-975b9.appspot.com',
    measurementId: 'G-MXR2KSQXHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZNGGWY0l0m_VlWv90SVZCXxVdq0x2PMs',
    appId: '1:946278867566:android:6e32ad02daeb6084413c7f',
    messagingSenderId: '946278867566',
    projectId: 'flutterschool-975b9',
    storageBucket: 'flutterschool-975b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4PPy4TYrilQ_oCSlSG4O9v66FhDwHg0M',
    appId: '1:946278867566:ios:6fa664191761efe6413c7f',
    messagingSenderId: '946278867566',
    projectId: 'flutterschool-975b9',
    storageBucket: 'flutterschool-975b9.appspot.com',
    iosClientId: '946278867566-necvfnfef5g92vljshe0b7dafrv8d44h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4PPy4TYrilQ_oCSlSG4O9v66FhDwHg0M',
    appId: '1:946278867566:ios:6fa664191761efe6413c7f',
    messagingSenderId: '946278867566',
    projectId: 'flutterschool-975b9',
    storageBucket: 'flutterschool-975b9.appspot.com',
    iosClientId: '946278867566-necvfnfef5g92vljshe0b7dafrv8d44h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
